package activitat5.entity;
// Generated 28/02/2020 17:45:48 by Hibernate Tools 4.3.1



/**
 * Moviment generated by hbm2java
 */
public class Moviment  implements java.io.Serializable {


     private MovimentId id;
     private Partida partida;
     private String taulell;

    public Moviment() {
    }

	
    public Moviment(MovimentId id, Partida partida) {
        this.id = id;
        this.partida = partida;
    }
    public Moviment(MovimentId id, Partida partida, String taulell) {
       this.id = id;
       this.partida = partida;
       this.taulell = taulell;
    }
   
    public MovimentId getId() {
        return this.id;
    }
    
    public void setId(MovimentId id) {
        this.id = id;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public String getTaulell() {
        return this.taulell;
    }
    
    public void setTaulell(String taulell) {
        this.taulell = taulell;
    }




}


