package activitat5.entity;
// Generated 28/02/2020 17:45:48 by Hibernate Tools 4.3.1



/**
 * MovimentId generated by hbm2java
 */
public class MovimentId  implements java.io.Serializable {


     private int partidaId;
     private int numMoviment;

    public MovimentId() {
    }

    public MovimentId(int partidaId, int numMoviment) {
       this.partidaId = partidaId;
       this.numMoviment = numMoviment;
    }
   
    public int getPartidaId() {
        return this.partidaId;
    }
    
    public void setPartidaId(int partidaId) {
        this.partidaId = partidaId;
    }
    public int getNumMoviment() {
        return this.numMoviment;
    }
    
    public void setNumMoviment(int numMoviment) {
        this.numMoviment = numMoviment;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MovimentId) ) return false;
		 MovimentId castOther = ( MovimentId ) other; 
         
		 return (this.getPartidaId()==castOther.getPartidaId())
 && (this.getNumMoviment()==castOther.getNumMoviment());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPartidaId();
         result = 37 * result + this.getNumMoviment();
         return result;
   }   


}


